### ISSUE TITLE
feature request: flock support

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-quintain#26]
Quintain currently has explicit dependencies on ssg.  It should be ported to flock since that is now the default in bedrock so that you don't have to use a special bedrock configuration for quintain.

Low priority.

@mdorier

**Comment by mdorier** [comment]
From what I see, the only use of SSG is to get the protocol used by the servers, then the address of rank 0, correct?

**Comment by carns** [comment]
That's right.  The server side isn't doing anything with it, and the clients are just using the ssg file emitted by bedrock for basic connection info.

**Comment by mdorier** [comment]
Ok I submitted a PR: https://github.com/mochi-hpc/mochi-quintain/pull/27

**Comment by carns** [comment]
pr merged and issue complete
